language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

before_install:
  - sudo apt-get install docker

# command to install dependencies
install:
  - "pip install -r requirements.txt"

services: docker

before_script:
  - sudo systemctl start docker

# command to run tests
script: nosetests
