language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get install docker.io

# command to install dependencies
install:
  - "pip install -r requirements.txt"

services: docker

# command to run tests
script: nosetests
